### ISSUE TITLE
AstroLink not showing on conda-forge

### ISSUE THREAD

**Issue by william-h-oliver** [conda-forge/astrolink-feedstock#4]
### Comment:

Hi @conda-forge/core, astrolink is currently not showing on conda-forge (I think this is due to the feedstock having been rendered before https://github.com/conda-forge/status/issues/181 was resolved).

Could you please let me know how to fix this?

**Comment by dopplershift** [comment]
Try pushing an empty commit to main here:
```
git commit --allow-empty -m 'Empty commit to trigger Azure'
```

**Comment by ocefpaf** [comment]
BTW, I just restart the Azure job.

**Comment by jakirkham** [comment]
Thanks Filipe! 🙏

Appears to be resolved

<img width="1840" alt="Screenshot 2024-07-09 at 12 24 18 PM" src="https://github.com/conda-forge/astrolink-feedstock/assets/3019665/11905083-3ca7-4064-9423-5589816763e9">

**Comment by william-h-oliver** [comment]
Great! Thank you
